@Messaging_App_HostAddress = https://localhost:7227

POST {{Messaging_App_HostAddress}}/auth/register
Content-Type: application/json

{
  "username": "testuser11",
  "email": "test@email.com11",
  "password": "Test"
}

###

POST {{Messaging_App_HostAddress}}/auth/login
Content-Type: application/json

{
  "username": "testuser11",
  "password": "Test"

}

###
