@Messaging_App_HostAddress = https://localhost:7227

POST {{Messaging_App_HostAddress}}/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "email": "test@email.com",
  "password": "Test"
}

###
