@Messaging_App_HostAddress = https://localhost:7227
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdHVzZXIyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIyIiwiZXhwIjoxNzcyNjA4ODc0LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0IiwiYXVkIjoiTWVzc2FnaW5nQXBwQVBJIn0.dvpDJjO_WHwK4kyO_8qCGweHSlu-N4UoLf0vElEFAiU
@id = 1
@code = 019cb7aa-e2e9-7e78-8501-c97f8ae38506

###Create invite
POST {{Messaging_App_HostAddress}}/server/{{id}}/invite
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "expiresDate": null,
  "maxUses": null
}

###Get invites for server
GET {{Messaging_App_HostAddress}}/server/{{id}}/invites
Authorization: Bearer {{accessToken}}

###Delete invite
DELETE {{Messaging_App_HostAddress}}/server/{{id}}/invite/{{code}}
Authorization: Bearer {{accessToken}}

###Join server via invite
POST {{Messaging_App_HostAddress}}/invite/{{code}}/join
Content-Type: application/json
Authorization: Bearer {{accessToken}}
